FROM node:20-alpine

# Install Python3 and FFmpeg (Critical for yt-dlp)
RUN apk add --no-cache python3 ffmpeg

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Declare Build Arguments (Required for Next.js to find env vars during build)
ARG NEXT_PUBLIC_GEMINI_API_KEY
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_BASE_URL
ARG POLAR_ACCESS_TOKEN
ARG POLAR_SANDBOX
ARG NEXT_PUBLIC_POLAR_PRO_PRODUCT_ID
ARG NEXT_PUBLIC_POLAR_PREMIUM_PRODUCT_ID
ARG NEXT_PUBLIC_POLAR_CREDITS_PRO_PRODUCT_ID
ARG NEXT_PUBLIC_POLAR_CREDITS_PREMIUM_PRODUCT_ID

# Make them available as environment variables during build
ENV NEXT_PUBLIC_GEMINI_API_KEY=$NEXT_PUBLIC_GEMINI_API_KEY
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV POLAR_ACCESS_TOKEN=$POLAR_ACCESS_TOKEN
ENV POLAR_SANDBOX=$POLAR_SANDBOX
ENV NEXT_PUBLIC_POLAR_PRO_PRODUCT_ID=$NEXT_PUBLIC_POLAR_PRO_PRODUCT_ID
ENV NEXT_PUBLIC_POLAR_PREMIUM_PRODUCT_ID=$NEXT_PUBLIC_POLAR_PREMIUM_PRODUCT_ID
ENV NEXT_PUBLIC_POLAR_CREDITS_PRO_PRODUCT_ID=$NEXT_PUBLIC_POLAR_CREDITS_PRO_PRODUCT_ID
ENV NEXT_PUBLIC_POLAR_CREDITS_PREMIUM_PRODUCT_ID=$NEXT_PUBLIC_POLAR_CREDITS_PREMIUM_PRODUCT_ID

# Copy source
COPY . .

# Build
RUN npm run build

# Start
EXPOSE 3000
CMD ["npm", "start"]
